<a href="https://colab.research.google.com/github/Aiviloxii/Playground2/blob/main/W4_C2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##Arrays

In [2]:
first_array = np.array([1,2,3,4,5]) #creating from a list

In [3]:
type(first_array)

numpy.ndarray

In [4]:
tup_array = np.array((6,7,8,9,0)) #creating from a tuple

Datatypes used in numpy
- int
- float
- unit(unsigned integer)

arrays convert all items to a single datatype unless specified.

In [6]:
var_array = np.array([1,2,3.14,4,5])

In [7]:
var_array #it is seen here that all elements have been converted to float

array([1.  , 2.  , 3.14, 4.  , 5.  ])

In [10]:
array_2 = np.array([1,2.4,3],dtype='int64') #here the datatype is specified

In [11]:
array_2

array([1, 2, 3])

##Special Arrays

In [15]:
#an array of zeros
np.zeros((3,2), dtype='int')

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [17]:
#an array for ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#create an array for specific values
np.full(4, 7.6)

array([7.6, 7.6, 7.6, 7.6])

In [19]:
#create an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
#create a linear sequence
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.linspace(0,2,5)#evenly spaced array

array([0. , 0.5, 1. , 1.5, 2. ])

In [28]:

#creates an array of random numbers in a specific matrix
np.random.random((3,2))

array([[0.94091433, 0.77050102],
       [0.57068312, 0.94559401],
       [0.23039749, 0.01689891]])

In [32]:
#a normal random array matrix
np.random.normal(0,1,(2,2))

array([[-0.01810922, -0.35656077],
       [-1.0902765 , -0.04039374]])

In [34]:
np.random.randint(1,10,(3,2)) #creates a matrix of random integer

array([[1, 5],
       [6, 4],
       [3, 8]])

##Array Attributes

ndim

In [35]:
array_1d = first_array

In [36]:
array_1d.ndim #checks the dimension of the array

1

In [37]:

#this has one [] enveloping the values
array_2d = np.array([[1,2,3],[4,5,6]])

In [38]:
array_2d.ndim

2

In [41]:
#this has two [] enveloping the values
array_3d = np.array([[[0,9,8]]])

In [42]:
array_3d.ndim

3

##shape attributes
shows the rows and columns

In [43]:
array_1d

array([1, 2, 3, 4, 5])

In [44]:
array_1d.shape

(5,)

In [45]:
array_3d

array([[[0, 9, 8]]])

In [46]:
array_3d.shape

(1, 1, 3)

In [47]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
array_2d.shape

(2, 3)

##size attribute

shows number of elements

In [49]:
array_2d.size

6

In [50]:
array_3d.size

3

##Array Indexing

In [51]:
x = array_2

In [53]:
x[0]

np.int64(1)

In [54]:
y = np.array([[3,4,5], [1,2,6], [8,9,0]])

In [55]:
y

array([[3, 4, 5],
       [1, 2, 6],
       [8, 9, 0]])

In [56]:
y.shape

(3, 3)

In [57]:
y.size

9

In [58]:
y[0,2]

np.int64(5)

In [60]:
y[2,0] = 0

In [61]:
y

array([[3, 4, 5],
       [1, 2, 6],
       [0, 9, 0]])

In [64]:
y[:, :2]

array([[3, 4],
       [1, 2],
       [0, 9]])

In [66]:
y[:2, :2]

array([[3, 4],
       [1, 2]])

#Reshaping Arrays

In [67]:
z = np.arange(12)

In [68]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
new_z = z.reshape(2,6)
new_z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

##Concatenation and splitting arrays

In [77]:
a = np.array([1,0,2])
b = np.array([3,6,4])

In [78]:
ab = np.concatenate([a,b])

In [79]:
ab

array([1, 0, 2, 3, 6, 4])

In [82]:
np.concatenate([y,y], axis=1) #axis makes them lap side by side

array([[3, 4, 5, 3, 4, 5],
       [1, 2, 6, 1, 2, 6],
       [0, 9, 0, 0, 9, 0]])

In [83]:
#hstack concatenates horizontally
np.hstack([y,y])

array([[3, 4, 5, 3, 4, 5],
       [1, 2, 6, 1, 2, 6],
       [0, 9, 0, 0, 9, 0]])

In [85]:
#vstack concatenates vertically
np.vstack([y,y])

array([[3, 4, 5],
       [1, 2, 6],
       [0, 9, 0],
       [3, 4, 5],
       [1, 2, 6],
       [0, 9, 0]])

In [86]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
m,n = np.split(z, [5])

In [88]:
m

array([0, 1, 2, 3, 4])

In [89]:
n

array([ 5,  6,  7,  8,  9, 10, 11])

In [90]:
m,n,o = np.split(z, [4, 8])

In [91]:
m

array([0, 1, 2, 3])

In [92]:
n

array([4, 5, 6, 7])

In [93]:
o

array([ 8,  9, 10, 11])

##Creating copies

In [94]:
z_copy = z.copy()

In [95]:
z_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])